config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show

  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit

  end

  def update

    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end


  def destroy
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="form-container">
  <%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>
<%= link_to 'Annuler', flats_path %>
</div>

app/views/flats/edit.html.erb
<h1>Edit a flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/index.html.erb
<div class="index-header">
  <h1>Welcome to AirBnB</h1>
  <%= link_to 'Create New Flat', new_flat_path %>
</div>

<div class="index-container">

<% @flats.each do |flat| %>


    <div class="index-card">
      <div class="index-card-img">

      </div>
      <div class="index-card-infos">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
      </div>

      <div class="index-card-logo">
        <i class="fa-solid fa-person">  <%= flat.number_of_guests %> </i>
        <i class="fa-solid fa-euro-sign">  <%= flat.price_per_night %></i>
      </div>

      <div class="index-card-link">
        <%= link_to 'More info', flat_path(flat) %>
        <%= link_to 'Edit', edit_flat_path(flat) %>
        <%= link_to 'Delete', flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

      </div>
    </div>

<% end %>

</div>

<%# t.string "name"
    t.string "address"
    t.text "description"
    t.integer "price_per_night"
    t.integer "number_of_guests" %>

app/views/flats/new.html.erb
  <h1>Create a new flat</h1>
<%= render "form", flat: @flat %>

app/views/flats/show.html.erb
<div class="show-card-header">

</div>
<div class="show-container">

  <div class="show-card-details show-card-parent">
    <div class="show-card">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
    </div>
    <div class="show-card">
      <h4>A bit more about this flat..</h4>
      <p><%= @flat.description %></p>
    </div>
  </div>

  <div class="show-book-card show-card-parent">
    <div class="show-card">
      <h4>Book this place</h4>
      <label for="start_date">From :</label>
      <input type="date" id="start_date" name="start_date">

      <label for="end_date">To :</label>
      <input type="date" id="end_date" name="end_date">

       <button type="submit" class="book-button">Book</button>
    </div>
    <div class="show-card">
      <h4>Details</h4>
      <div class="detail-icon">
        <i class="fa-solid fa-person">  <%= @flat.number_of_guests %> </i>
        <i class="fa-solid fa-euro-sign">  <%= @flat.price_per_night %></i>
      </div>
    </div>
    <div class="show-card">
      <h6>Share</h6>
      <div class="share-icon">
        <i class="fa-brands fa-instagram"></i>
        <i class="fa-brands fa-twitter"></i>
        <i class="fa-brands fa-pinterest-p"></i>
        <i class="fa-solid fa-square-envelope"></i>
      </div>


    </div>
  </div>
</div>
 <%= link_to 'Back', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>